/**
 * File system utilities for code generation
 */
import crypto from "node:crypto"
import fs from "node:fs"
import path from "node:path"

/** Ensure a directory exists, creating it recursively if needed */
export function ensureDir(dirPath: string): void {
	if (!fs.existsSync(dirPath)) {
		fs.mkdirSync(dirPath, { recursive: true })
	}
}

/**
 * Atomically write and parse JSON (tmp + rename).
 * Preserves non-generated keys when merging.
 */
export function writeJsonAtomic(filePath: string, data: unknown): void {
	const dir = path.dirname(filePath)
	ensureDir(dir)
	const tmpPath = `${filePath}.${crypto.randomBytes(4).toString("hex")}.tmp`
	fs.writeFileSync(tmpPath, `${JSON.stringify(data, null, "\t")}\n`)
	fs.renameSync(tmpPath, filePath)
}

/** Check if a file exists */
export function fileExists(filePath: string): boolean {
	return fs.existsSync(filePath)
}

/** Read file content as string */
export function readFile(filePath: string): string {
	return fs.readFileSync(filePath, "utf-8")
}

function contentHash(content: string): string {
	return crypto.createHash("sha256").update(content).digest("hex").slice(0, 12)
}

function buildHeader(hash: string, generator: string, ext: string): string {
	if (ext === ".sql") return `-- @generated by ${generator} — do not edit. checksum: ${hash}`
	if (ext === ".txt") return `# @generated by ${generator} — do not edit. checksum: ${hash}`
	return `/* @generated by ${generator} — do not edit. checksum: ${hash} */`
}

function extractChecksum(line: string): string | null {
	const match = line.match(/checksum: ([0-9a-f]{12})/)
	return match?.[1] ?? null
}

/**
 * Write a generated file with a checksum header.
 * Skips the write when the existing file's checksum matches (idempotent).
 * Returns true if the file was written, false if skipped.
 */
export function writeGenFile(filePath: string, body: string, generator: string): boolean {
	const normalized = body.replace(/\n*$/, "\n")
	const hash = contentHash(normalized)

	const ext = filePath.endsWith(".d.ts") ? ".d.ts" : path.extname(filePath)
	const header = buildHeader(hash, generator, ext)
	const fullContent = `${header}\n${normalized}`

	try {
		const existing = fs.readFileSync(filePath, "utf-8")
		const firstLine = existing.split("\n")[0] ?? ""
		if (extractChecksum(firstLine) === hash) return false
	} catch {
		/* file does not exist — proceed to write */
	}

	const dir = path.dirname(filePath)
	ensureDir(dir)
	const tmpPath = `${filePath}.${crypto.randomBytes(4).toString("hex")}.tmp`
	fs.writeFileSync(tmpPath, fullContent)
	fs.renameSync(tmpPath, filePath)
	return true
}

/**
 * Write a generated JSON file with a `_generated` metadata key.
 * Skips the write when the existing file's checksum matches.
 * Returns true if the file was written, false if skipped.
 */
export function writeGenJsonFile(filePath: string, data: unknown, generator: string): boolean {
	const json = JSON.stringify(data, null, 2)
	const hash = contentHash(json)
	const marker = `${generator} checksum:${hash}`

	try {
		const existing = fs.readFileSync(filePath, "utf-8")
		const parsed = JSON.parse(existing) as Record<string, unknown>
		if (parsed["_generated"] === marker) return false
	} catch {
		/* file does not exist or is invalid JSON — proceed to write */
	}

	const output = { _generated: marker, ...(data as Record<string, unknown>) }
	const dir = path.dirname(filePath)
	ensureDir(dir)
	const tmpPath = `${filePath}.${crypto.randomBytes(4).toString("hex")}.tmp`
	fs.writeFileSync(tmpPath, `${JSON.stringify(output, null, 2)}\n`)
	fs.renameSync(tmpPath, filePath)
	return true
}
