import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"
import type { TableMeta } from "../../../../src/codegen/analyzer-types.ts"
import { generateEntities } from "../../../../src/codegen/generators/entities.ts"

function makeTable(varName: string, idPrefix: string | null): TableMeta {
	return {
		checkConstraints: [],
		fields: [],
		hasCompositePrimaryKey: false,
		idPrefix,
		sqlName: varName,
		timestamps: { createdAt: false, deletedAt: false, style: "camelCase", updatedAt: false },
		uniqueIndexes: [],
		varName,
	}
}

describe("generateEntities", () => {
	let tmpDir: string

	beforeEach(() => {
		tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "comb-gen-entities-"))
	})

	afterEach(() => {
		fs.rmSync(tmpDir, { force: true, recursive: true })
	})

	it("generates prefix map and typed helper", () => {
		const tables = [makeTable("user", "usr"), makeTable("organization", "org")]
		const output = path.join(tmpDir, "entities.gen.ts")

		generateEntities(tables, "test", { output }, tmpDir)

		const content = fs.readFileSync(output, "utf-8")
		expect(content).toContain("const entityPrefixes = {")
		expect(content).toContain('\torganization: "org",')
		expect(content).toContain('\tuser: "usr",')
		expect(content).toContain("} as const")
		expect(content).toContain("type EntityName = keyof typeof entityPrefixes")
		expect(content).toContain("function generateEntityId<T extends EntityName>(entity: T): string")
		expect(content).toContain("return generateId(entityPrefixes[entity])")
	})

	it("exports generateUlid and EntityName type", () => {
		const tables = [makeTable("user", "usr")]
		const output = path.join(tmpDir, "entities.gen.ts")

		generateEntities(tables, "test", { output }, tmpDir)

		const content = fs.readFileSync(output, "utf-8")
		expect(content).toContain("export { entityPrefixes, generateEntityId, generateUlid, type EntityName }")
	})

	it("skips tables without idPrefix (serialId)", () => {
		const tables = [makeTable("user", "usr"), makeTable("counter", null), makeTable("project", "proj")]
		const output = path.join(tmpDir, "entities.gen.ts")

		generateEntities(tables, "test", { output }, tmpDir)

		const content = fs.readFileSync(output, "utf-8")
		expect(content).toContain('\tuser: "usr",')
		expect(content).toContain('\tproject: "proj",')
		expect(content).not.toContain("counter")
	})

	it("skips generation when no tables have prefixes", () => {
		const tables = [makeTable("counter", null), makeTable("sequence", null)]
		const output = path.join(tmpDir, "entities.gen.ts")

		generateEntities(tables, "test", { output }, tmpDir)

		expect(fs.existsSync(output)).toBe(false)
	})

	it("uses default @lovrozagar/comb import", () => {
		const tables = [makeTable("user", "usr")]
		const output = path.join(tmpDir, "entities.gen.ts")

		generateEntities(tables, "test", { output }, tmpDir)

		const content = fs.readFileSync(output, "utf-8")
		expect(content).toContain('import { generateId, generateUlid } from "@lovrozagar/comb"')
	})

	it("uses custom importFrom when provided", () => {
		const tables = [makeTable("user", "usr")]
		const output = path.join(tmpDir, "entities.gen.ts")

		generateEntities(tables, "test", { importFrom: "my-comb", output }, tmpDir)

		const content = fs.readFileSync(output, "utf-8")
		expect(content).toContain('import { generateId, generateUlid } from "my-comb"')
	})

	it("includes header comment with generation timestamp", () => {
		const tables = [makeTable("user", "usr")]
		const output = path.join(tmpDir, "entities.gen.ts")

		generateEntities(tables, "test", { output }, tmpDir)

		const content = fs.readFileSync(output, "utf-8")
		expect(content).toContain("@generated by comb")
		expect(content).toContain("do not edit")
		expect(content).toMatch(/checksum: [\da-f]+/)
	})

	it("updates package.json with ./entities export", () => {
		const pkgPath = path.join(tmpDir, "package.json")
		fs.writeFileSync(pkgPath, JSON.stringify({ exports: { ".": "./src/index.ts" }, name: "test" }))

		/* entities output is in a src/ subdirectory */
		const srcDir = path.join(tmpDir, "src")
		fs.mkdirSync(srcDir)
		const output = path.join(srcDir, "db.test.entities.gen.ts")

		const tables = [makeTable("user", "usr")]
		generateEntities(tables, "test", { output, updatePackageJson: true }, tmpDir)

		const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8")) as Record<string, unknown>
		const exports = pkg.exports as Record<string, string>
		expect(exports["./entities"]).toBe("./src/db.test.entities.gen.ts")
		expect(exports["."]).toBe("./src/index.ts")
	})

	it("replaces existing ./entities export on re-run", () => {
		const pkgPath = path.join(tmpDir, "package.json")
		fs.writeFileSync(
			pkgPath,
			JSON.stringify({
				exports: { ".": "./src/index.ts", "./entities": "./old-path.ts" },
				name: "test",
			}),
		)

		const output = path.join(tmpDir, "db.test.entities.gen.ts")
		const tables = [makeTable("user", "usr")]
		generateEntities(tables, "test", { output, updatePackageJson: true }, tmpDir)

		const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8")) as Record<string, unknown>
		const exports = pkg.exports as Record<string, string>
		expect(exports["./entities"]).toBe("./db.test.entities.gen.ts")
	})
})
