import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"
import type { FieldMeta, TableMeta } from "../../../../src/codegen/analyzer-types.ts"
import { generateFieldNames } from "../../../../src/codegen/generators/field-names.ts"

function field(name: string): FieldMeta {
	return {
		constraints: {
			autogenerate: false,
			email: false,
			lowercase: false,
			max: null,
			maxBytes: null,
			min: null,
			nomutate: false,
			password: false,
			pattern: null,
			private: false,
			tenant: false,
			trim: false,
			uppercase: false,
			url: false,
		},
		drizzleHelper: "text",
		enumName: null,
		enumValues: null,
		states: null,
		foreignKey: null,
		isNotNull: false,
		isPrimaryKey: name === "id",
		jsonSchemaName: null,
		length: null,
		name,
		raw: `c.text("${name}")`,
	}
}

function table(sqlName: string, fieldNames: string[]): TableMeta {
	return {
		checkConstraints: [],
		fields: fieldNames.map(field),
		hasCompositePrimaryKey: false,
		idPrefix: null,
		sqlName,
		timestamps: { createdAt: false, deletedAt: false, style: "snake_case", updatedAt: false },
		uniqueIndexes: [],
		varName: sqlName,
	}
}

describe("generateFieldNames", () => {
	let tmpDir: string

	beforeEach(() => {
		tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "comb-field-names-"))
	})

	afterEach(() => {
		fs.rmSync(tmpDir, { force: true, recursive: true })
	})

	function generate(tables: TableMeta[], dbName = "core", updatePackageJson = false): string {
		const output = path.join(tmpDir, "field-names.gen.ts")
		generateFieldNames(tables, dbName, { output, updatePackageJson }, tmpDir)
		return fs.existsSync(output) ? fs.readFileSync(output, "utf-8") : ""
	}

	it("emits a const and type named from the database", () => {
		const content = generate([table("post", ["id", "title"])], "core")
		expect(content).toContain("const CORE_DB_FIELD_NAMES = {")
		expect(content).toContain("type CoreDbFieldName = keyof typeof CORE_DB_FIELD_NAMES")
		expect(content).toContain("export { CORE_DB_FIELD_NAMES, type CoreDbFieldName }")
	})

	it("carries the generated header", () => {
		const content = generate([table("post", ["id"])])
		expect(content).toContain("@generated by comb")
	})

	it("humanises snake_case into a label", () => {
		const content = generate([table("post", ["minute_read"])])
		expect(content).toContain('minute_read: "Minute read"')
	})

	it("strips a _json suffix", () => {
		const content = generate([table("post", ["settings_json"])])
		expect(content).toContain('settings_json: "Settings"')
	})

	it("strips a _id suffix but keeps a bare id", () => {
		const content = generate([table("post", ["author_id", "id"])])
		expect(content).toContain('author_id: "Author"')
		expect(content).toContain('id: "Id"')
	})

	it("marks entries whose label was altered by suffix stripping", () => {
		const content = generate([table("post", ["author_id", "title"])])
		expect(content).toContain("/* was author_id */")
		/* an unaltered label needs no note */
		expect(content).toMatch(/title: "Title",\s*$/m)
	})

	it("deduplicates a field name shared across tables", () => {
		const content = generate([table("post", ["id", "title"]), table("page", ["id", "title"])])
		expect(content.match(/^\ttitle:/gm)).toHaveLength(1)
		expect(content.match(/^\tid:/gm)).toHaveLength(1)
	})

	it("sorts entries so regeneration is stable regardless of table order", () => {
		const forward = generate([table("post", ["zebra", "apple"])])
		fs.rmSync(path.join(tmpDir, "field-names.gen.ts"))
		const reversed = generate([table("post", ["apple", "zebra"])])
		expect(reversed).toBe(forward)
		expect(forward.indexOf("apple:")).toBeLessThan(forward.indexOf("zebra:"))
	})

	it("skips underscore-prefixed internal fields", () => {
		const content = generate([table("post", ["_search", "title"])])
		expect(content).not.toContain("_search:")
		expect(content).toContain("title:")
	})

	it("writes nothing when every field is skipped", () => {
		expect(generate([table("post", ["_search"])])).toBe("")
	})

	it("writes nothing when there are no tables", () => {
		expect(generate([])).toBe("")
	})

	it("registers a ./field-names export when asked", () => {
		fs.writeFileSync(path.join(tmpDir, "package.json"), JSON.stringify({ exports: {}, name: "app" }))
		generate([table("post", ["id"])], "core", true)

		const pkg = JSON.parse(fs.readFileSync(path.join(tmpDir, "package.json"), "utf-8")) as {
			exports: Record<string, string>
		}
		expect(pkg.exports["./field-names"]).toBe("./field-names.gen.ts")
	})

	it("preserves unrelated exports and replaces its own on a rerun", () => {
		fs.writeFileSync(
			path.join(tmpDir, "package.json"),
			JSON.stringify({ exports: { ".": "./index.ts", "./field-names": "./stale.ts" }, name: "app" }),
		)
		generate([table("post", ["id"])], "core", true)

		const pkg = JSON.parse(fs.readFileSync(path.join(tmpDir, "package.json"), "utf-8")) as {
			exports: Record<string, string>
		}
		expect(pkg.exports["."]).toBe("./index.ts")
		expect(pkg.exports["./field-names"]).toBe("./field-names.gen.ts")
	})
})
