import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"
import {
	ensureDir,
	fileExists,
	readFile,
	writeGenFile,
	writeGenJsonFile,
	writeJsonAtomic,
} from "../../../../src/codegen/utils/fs.ts"

describe("codegen/utils/fs", () => {
	let tmpDir: string

	beforeEach(() => {
		tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "comb-fs-test-"))
	})

	afterEach(() => {
		fs.rmSync(tmpDir, { force: true, recursive: true })
	})

	describe("ensureDir", () => {
		it("creates nested directories", () => {
			const nested = path.join(tmpDir, "a", "b", "c")
			ensureDir(nested)
			expect(fs.existsSync(nested)).toBe(true)
		})

		it("does not throw if already exists", () => {
			ensureDir(tmpDir)
			expect(fs.existsSync(tmpDir)).toBe(true)
		})
	})

	describe("writeJsonAtomic", () => {
		it("writes formatted JSON with trailing newline", () => {
			const fp = path.join(tmpDir, "data.json")
			writeJsonAtomic(fp, { a: 1, b: "two" })
			const content = fs.readFileSync(fp, "utf-8")
			expect(content).toBe('{\n\t"a": 1,\n\t"b": "two"\n}\n')
		})
	})

	describe("fileExists", () => {
		it("returns true for existing file", () => {
			const fp = path.join(tmpDir, "exists.txt")
			fs.writeFileSync(fp, "")
			expect(fileExists(fp)).toBe(true)
		})

		it("returns false for missing file", () => {
			expect(fileExists(path.join(tmpDir, "nope.txt"))).toBe(false)
		})
	})

	describe("readFile", () => {
		it("reads file content", () => {
			const fp = path.join(tmpDir, "read.txt")
			fs.writeFileSync(fp, "hello world")
			expect(readFile(fp)).toBe("hello world")
		})
	})

	describe("writeGenFile", () => {
		it("writes .ts file with checksum header", () => {
			const fp = path.join(tmpDir, "out.gen.ts")
			writeGenFile(fp, "export const x = 1\n", "comb")
			const content = fs.readFileSync(fp, "utf-8")
			expect(content).toMatch(/^\/\* @generated by comb — do not edit\. checksum: [0-9a-f]{12} \*\/\n/)
			expect(content).toContain("export const x = 1\n")
		})

		it("writes .sql file with SQL comment header", () => {
			const fp = path.join(tmpDir, "schema.gen.sql")
			writeGenFile(fp, "CREATE TABLE t (id INTEGER);\n", "comb")
			const content = fs.readFileSync(fp, "utf-8")
			expect(content).toMatch(/^-- @generated by comb — do not edit\. checksum: [0-9a-f]{12}\n/)
		})

		it("writes .txt file with hash comment header", () => {
			const fp = path.join(tmpDir, "notes.gen.txt")
			writeGenFile(fp, "hello\n", "comb")
			const content = fs.readFileSync(fp, "utf-8")
			expect(content).toMatch(/^# @generated by comb — do not edit\. checksum: [0-9a-f]{12}\n/)
		})

		it("skips write when checksum matches existing file", () => {
			const fp = path.join(tmpDir, "skip.gen.ts")
			writeGenFile(fp, "const a = 1\n", "comb")
			const stat1 = fs.statSync(fp).mtimeMs

			/* small delay so mtime would differ if rewritten */
			const wrote = writeGenFile(fp, "const a = 1\n", "comb")
			expect(wrote).toBe(false)
			expect(fs.statSync(fp).mtimeMs).toBe(stat1)
		})

		it("rewrites when content differs from existing file", () => {
			const fp = path.join(tmpDir, "change.gen.ts")
			writeGenFile(fp, "const a = 1\n", "comb")
			const wrote = writeGenFile(fp, "const a = 2\n", "comb")
			expect(wrote).toBe(true)
			expect(fs.readFileSync(fp, "utf-8")).toContain("const a = 2")
		})

		it("creates parent directories if missing", () => {
			const fp = path.join(tmpDir, "deep", "nested", "out.gen.ts")
			writeGenFile(fp, "export {}\n", "comb")
			expect(fs.existsSync(fp)).toBe(true)
		})

		it("normalizes trailing newlines", () => {
			const fp = path.join(tmpDir, "trail.gen.ts")
			writeGenFile(fp, "const a = 1\n\n\n", "comb")
			const content = fs.readFileSync(fp, "utf-8")
			expect(content).toMatch(/const a = 1\n$/)
		})
	})

	describe("writeGenJsonFile", () => {
		it("writes JSON with _generated key", () => {
			const fp = path.join(tmpDir, "data.gen.json")
			writeGenJsonFile(fp, { count: 5, name: "test" }, "comb")
			const content = JSON.parse(fs.readFileSync(fp, "utf-8")) as Record<string, unknown>
			expect(content._generated).toMatch(/^comb checksum:[0-9a-f]{12}$/)
			expect(content.name).toBe("test")
			expect(content.count).toBe(5)
		})

		it("skips write when checksum matches", () => {
			const fp = path.join(tmpDir, "same.gen.json")
			writeGenJsonFile(fp, { a: 1 }, "comb")
			const wrote = writeGenJsonFile(fp, { a: 1 }, "comb")
			expect(wrote).toBe(false)
		})

		it("rewrites when data changes", () => {
			const fp = path.join(tmpDir, "diff.gen.json")
			writeGenJsonFile(fp, { a: 1 }, "comb")
			const wrote = writeGenJsonFile(fp, { a: 2 }, "comb")
			expect(wrote).toBe(true)
			const content = JSON.parse(fs.readFileSync(fp, "utf-8")) as Record<string, unknown>
			expect(content.a).toBe(2)
		})
	})
})
